[Audio]
Volume=100

[General]
LastPlayedFile=file:///run/media/jojo/disk/Games/Hitman-Absolution-Steamrip/Hitman Absolution/Hitman Professional Edition Extras/BURNING HOPE - THE MAKING OF HITMAN ABSOLUTION.mp4
