[services]
gog = True
egs = True
ea_app = True
ubisoft = True
steam = True
steam_in_games_view = True

[lutris]
library_ignores = 
migration_version = 17
width = 1165
height = 314
window_x = 45
window_y = 45
maximized = True
selected_category = category:all
show_advanced_options = True
sidebar_collapsed_sections = service
installer_create_desktop_shortcut = False
installer_create_menu_shortcut = True
filter_installed = False

